### ISSUE TITLE
💄 공통 컴포넌트 구축

### ISSUE THREAD

**Issue by whynot1217** [ggosunnae/ggosunnae_front#12]
## 어떤것을 작업하시나요?

> 공통 컴포넌트화 작업

## 작업 상세 내용

- [x] Like Toggle
- [x] Comment
- [x] Category
- [x] UserId
- [x] BookMarkToggle
- [x] InfoToggle
- [x] APP_BAR

**Comment by Banal972** [comment]
상세내용을 좋아요/북마크, 댓글, 카테고리, 유저아이디, 토글, 좋아요 버튼, APP_BAR
이렇게 적는게 좋을것 같아요!
